/**
 * As frases do J. Martins (@j.mar.tins66).
 *
 * O fecho "Pense nisso!" foi tirado de cada uma de proposito: ele virou o
 * botao que fecha o aviso, entao repeti-lo no texto soaria duas vezes.
 *
 * Fica em arquivo proprio e e carregado sob demanda — sao 419
 * frases, e nenhuma delas precisa estar no pacote de quem so quer abrir o app.
 */
export const FRASES: readonly string[] = [
  "O amor, é a única dívida que você paga todo dia e mesmo assim, continua devendo.",
  "Acordei hoje, me sentindo um beija -flor.",
  "Se jabuti não sobe em árvore, quem colocou esse infeliz lá.",
  "Seja uma mulher tão interessante, tão especial, que não restará ao homem outra alternativa a não ser te amar.",
  "Pai, voce foi meu herói meu bandido, hoje é mais muito mais que um amigo, nem você nem ninguém tá sozinho. Parabéns pais, parabéns.",
  "Amar quem não te ama, é como abraçar um Cacto, quanto mais você segura, mais dói.",
  "Abraço é coisa tão séria, que não se empresta, se dá. Então, vai meu abraço pra você.",
  "Acordei hoje me sentindo um beija-flor.",
  "Ninguem nunca me disse: você é meu mundo. talvez eu seja só um bairro.",
  "O inferno que eu passei, não tinha fogo, nem demônio, tinha pessoas, que eu tanto amava.",
  "Ela leva a vida inteira querendo casar, mas quando chega o dia, atrasa, pode isso.",
  "Não alimente todos os caes que você ve sofrer. Alguns, so precisam de forcas pra morder voce.",
  "Chegando do cardiologista agora, tá tudo bem com o coração. Foi identificada apenas uma paixonite aguda do miocardio, nada de mais.",
  "Tem gente tão azeda, que quando chupa limão, é a fruta que faz careta.",
  "Eu tava pensando aqui: eu tomo café e Claudia leite, eu venho da cidade e Vanessa da mata, eu gosto de maçã e Camila pitanga.",
  "Assim que o dia amanheceu Lá no mar alto da paixão Dava pra ver o tempo ruir Cadê você? Que solidão Esquecera de mim.",
  "Ser livre, é ter tempo para as as coisas que se ama: é abraçar, se entregar, sonhar, recomeçar tudo de novo.",
  "Eu só solto Pipa e Claudia Raia, eu gosto de Batman e Luciano Hulk, eu gosto de laranja e Gustavo Lima. Eu não queria publicar esse vídeo, mas a Kássia Kiss.",
  "Carne e unha, alma gêmea, bate coração, as metades da laranja, dois amantes dois irmãos. Duas forças que se atraem sonho lindo de viver, tô morrendo de vontade de você.",
  "Se algo de bom acontecer, faça uma viagem para comemorar, se algo de ruim acontecer, faça uma viagem para esquecer, se nada acontecer, faça uma viagem para que algo aconteça.",
  "Ai, você vai Tomar um chá pra se acalmar e no chá tá escrito: Mate.",
  "Hoje preciso de você com qualquer humor com qualquer sorriso.",
  "Escolha ser feliz e embarque nessa comigo também.",
  "Eu não sou assim tão forte o tempo todo, às vezes, preciso de colo também.",
  "Nunca fui picado por cobra ou escorpião, mas já senti na pele o veneno maligno da maldade humana.",
  "Deus removeu pessoas da sua vida, porque ele ouviu conversas que você não ouviu.",
  "Coração receitou: De oito em oito horas, uma dose de amor. Eu tomei, funcionou.",
  "Prove que me conhece: Cite uma coisa que eu sempre falo.",
  "Amor, só merece investimento, quando traz paz e não tormento.",
  "Jamais use o GPS para ir ao cemitério. Não é legal você ouvir: você chegou ao seu destino.",
  "Se você tiver algum problema comigo, por favor, vem buscar, afinal, o problema é seu e não meu.",
  "Sabe mulherada, como deixar um homem louco atrás de vocês? Pega o celular dele e sai correndo.",
  "Nem todo sonho tá na padaria, eu por exemplo, tô aqui.",
  "To mau da gripe. Só o seu chá cura a minha sinusite, renite e até o que não existe.",
  "As mulheres só não conquistaram o mundo, porque ainda estão decidindo qual é a roupa para ocasião.",
  "Nenhum mortal pode guardar um segredo. Se a boca se cala, falam as pontas dos dedos. (Sigmund Freud).",
  "Quando você quiser, é só chamar que eu vou.",
  "O que te encanta em uma pessoa.",
  "Sempre se acha um jeito, quando o negócio é amar.",
  "A vida é estranha, chegamos sem nada e lutamos por tudo e no final, deixamos tudo e partimos sem nada.",
  "Eu estava discutindo com o sal e ele me mandou calar a boca. Tá vendo que sal grosso.",
  "Tem pessoas, que são como músicas, tocam nossas vidas, mas tem aquela especial, que é a nossa trilha sonora.",
  "Pessoas são como músicas: umas nós gostamos desde o início, outras, com o tempo.",
  "Não ligue pra tristeza, ela não tem telefone.",
  "A Amizade acaba, quando você percebe que o amigo, é só você.",
  "Se a vida se tornar uma barra, que seja de chocolate.",
  "Se não é amor, porque você me olha desse jeito.",
  "Meu coração queria ir até você, mas eu falei pra ele que sem ele eu morro e ele me respondeu que sem você ele não vive.",
  "A única coisa que você consegue sem esforço na vida, é peso, o resto meu amigo, é luta.",
  "Tem gente que dorme com as galinhas e o pior, acorda com elas também.",
  "A vaca bebe água e transforma em leite, a cobra bebê a mesma água e transforma em veneno. O que as pessoas transbordam, revela a essência delas.",
  "O amor é para os disponíveis, há viver, há viver dias incríveis.",
  "O amor deve ser igual café: às vezes forte, às vezes doce, às vezes só, às vezes acompanhado, porém, nunca frio.",
  "Bater em mulher e dizer que surtou é fácil, nunca vi ninguém surtar e ir capinar um quintal.",
  "Se uma pessoa te enganar uma vez, ela merece uma surra, mas se ela te enganar duas vezes, quem merece a surra, é você.",
  "Eu já sei que é assim, sem você está faltando a metade de mim.",
  "Não se admire se um dia um beija flore invadir a porta da sua casa te der um beijo e partir, fui eu que mandei um beijo que é.",
  "Eu só quero seu amor no meu coração meu amor é mais que Uma paixão.",
  "Acordei me sentindo tão bem, que parecia que você estava aqui.",
  "Em média, uma mulher se apaixona 7 vezes por ano, em 6 delas por sapatos.",
  "Ei, você aí que tá solteira: às vezes a sua alma gêmea, foi aquele pedreiro que fez psiu e foi ignorado.",
  "Será que outro Adão entrou no meu paraíso.",
  "O amor, é a maior de todas as forças terapêuticas, portanto, lance fora toda ansiedade e medo e ame muito.",
  "Atenção, atenção, mulher é dada como morta após ficar 30 minutos sem reclamar de nada.",
  "Sorria, pois na velhice, você não terá dentes.",
  "O peixes morre pela boca e muita gente, pela língua.",
  "Nesse romance existem lances sensacionais, mas te dá meu amor, jamais.",
  "Os maus amigos são um abismo, entre você e o fracasso.",
  "Uma mulher irritada é capaz de falar duas horas e no final dizer: Prefiro ficar calada.",
  "Às vezes, amor muda na forma, mas não deixa de existir.",
  "Não chore, pelo que lhe foi tirado, aprenda amar o que lhe foi dado.",
  "Ao perdoar, você arranca o poder do seu inimigo.",
  "O barulho de uma mulher, não é perigoso, mas o silêncio, pode ser fatal.",
  "Quando você estiver triste cante, você vai perceber que a sua voz é bem pior do que os seus problemas.",
  "Mãos que doam amor, nuunca ficam vazias.",
  "O barulho da mulher, não é perigoso, mas o silêncio, pode ser fatal.",
  "Homem é homem e biscoito é biscoito. E você o que é? Um homem ou um biscoito.",
  "Hoje eu estou igual a brigadeiro, você gosta.",
  "Os ventos que nos tiram algo que nós amamos, são os mesmos que nos trazem algo que aprendemos a amar.",
  "Homem que chora, que demonstra sentimento, que trata a mulher como merece, não é Gay, é raro.",
  "Razao: É quando o cuidado aproveita que a emoção tá dormindo e assume o mandato.",
  "Dizem, que quando não conseguimos dormir a noite, é porque estamos acordados no sonho de alguém.",
  "Os bons amigos, são umas ponte entre você e o sucesso.",
  "Cuidado onde você lança a sua âncora, nem todo porto é seguro.",
  "Eu não sei o que você está passando, mas espero que seja café.",
  "Uma pessoa não muda quando você quer, ela muda quando percebe a importância que você tem na vida dela.",
  "Eu falo comigo mesmo, só não respondo, porque não gosto de dá confiança a gente louca.",
  "Não é todo mundo que vai entender o seu caminho, mas tudo bem, não é o caminho deles, é o seu.",
  "Que diabo de amor é esse, que diz amar o outro e manda o outro andar.",
  "Entre todas as escolhas, eu continuo escolhendo você.",
  "Grande parte das pessoas, abre mão do amor próprio pra amar outra pessoa. E esse é o caminho para o sofrimento.",
  "Quando você não sabe se colocar no lugar do outro, a vida vem e coloca a gente lá, pra aprender na prática.",
  "Se você pudesse sentar no banco da praça e conversar com alguém por uma hora, quem seria.",
  "Hoje eu acordei, me sentindo um pão, doce.",
  "A gente ama verdadeiramente uma vez, as outras, são puras fantasias.",
  "É menina, se a pizza que vem de moto, demora, imagina o seu príncipe, que vem a cavalo.",
  "Quando foi a última vez que alguém olhou pra você, te deu um beijo e te disse: eu te amo.",
  "O beijo, é a menor distância entre dois apaixonados.",
  "De amor, eu não morro, o que eu posso, é chorar de saudade.",
  "Se você quer algo que nunca teve, faça algo que nunca fez.",
  "Lei da vida:Eu sinto, você não sente, eu demonstro, você despreza, eu desisto, você começa a se importar.",
  "Alguns homens querendo porte de armas, mas não tem pontaria nem pra mixar no vaso.",
  "É loucura desistir de todos seus sonhos, só porque um não se realizou.",
  "Sei que eu não sou perfeito, mas eu tô na moda.",
  "Tem coisas na gente, que só a gente entende.",
  "O que passa realmente, na cabeça de uma mulher apaixonada.",
  "Os grandes amores, são assim mesmo, eles nos dão o caminho da emoção.",
  "Amor, só existe a dois, amor sozinho, chama-se tristeza.",
  "O amor, é a única coisa que cresce a medida que se reparte.",
  "E tão bom morrer de amor e continuar vivendo.",
  "Se eu for aí tomar um café com você, que cidade eu vou.",
  "Um lobo em silêncio, impõe mais respeito do que um cachorro latindo.",
  "Lucidez, é um acesso de loucura ao contrário.",
  "Na sua opinião, uma grande amizade pode virar paixão? Sim ou não.",
  "Culpa, é quando você cisma que podia ter feito diferente, mas geralmente não podia.",
  "Não são as coisas bonitas que marcam nossas vidas, mas as pessoas que tem o dom de jamais serem esquecidas.",
  "A paciência é uma árvore amarga, mas de fruto muito doce.",
  "Uma mulher calada, é uma pistola com silenciador.",
  "Tome seu café em paz e se vire com seus B os, porque a vida meu amigo, não é um morango de amor.",
  "Nunca despreze alguém, que faria tudo por você.",
  "Quando a tristeza bater a sua porta, abra um belo sorriso e diga: desculpa, mas a felicidade chegou primeiro.",
  "A saudade só é bonita na poesia, na vida real ela arde.",
  "Diga ao seu avô que se vai e vem fosse e viesse, vai e vem iria, mas como vai e vem vai e não vem, vai e vem não vai.",
  "Alô fofoqueiras, vou fazer uma feijoada, que tal trazer a língua.",
  "E bobagem condenar todas as amizades, só porque uma te traiu.",
  "O coração da mulher, é como alguns instrumentos, depende de quem toca.",
  "E injusto não acreditar no amor, só porque um deles te foi infiel.",
  "Os verdadeiros amigos permanecem. Um brinde a eles.",
  "EU quero que você não pense nada triste, porque se o amor existe, o que não existe, é tempo pra sofrer.",
  "Felicidade, é um agora, que não tem pressa nenhuma.",
  "Tem palavras que chegam como um abraço e tem abraços que não precisam de palavras.",
  "Cuide bem desse lugar bonito, chamado você.",
  "Cuidado com as palavras duras ditas as pessoas, porque elas podem voltar contra você duramente e fazer um estrago muito maior.",
  "Certas coisas precisam acabar, antes que elas acabem com você.",
  "Liberdade na vida é ter um amor pra se prender.",
  "Eu aprendi com os erros, que a gente só é feliz, quando tenta.",
  "Os homens distingue-se pelo que fazem, as mulheres pelo que levam os homens a fazerem.",
  "Hoje eu amanheci com vontade de te dá um abraço. Um grande abraço.",
  "Dica pra achar a mulher ou o homem dos seus sonhos: Vá dormir.",
  "Onde o amor não puder entrar, não quero passar nem pela porta.",
  "É melhor não tá, do que tá e não tá. Entendeu.",
  "Amor verdadeiro, é aquele que o tempo não leva e a distancia não separa.",
  "E loucura desistir de todos os esforços só porque um deles fracassou.",
  "O abraço pode significar tanto e tantas coisas, ao mesmo tempo.",
  "Quem tava com você quando o bagulho ficou doido.",
  "Tristeza, é uma mão gigante que aperta o coração.",
  "Que queres que te diga além de que te amo? Se o que quero dizer-te é que te amo.",
  "Amo como ama o amor, não conheço outra razão para amar se não amar.",
  "Se o passado é uma roupa que não serve mais, o presente precisa ser ajustado pra caber melhor no futuro.",
  "Não espere ter tudo para aproveitar a vida, você já tem a vida pra aproveitar tudo.",
  "So tempo é capaz de entender um grande amor.",
  "Lembre-se, que sempre haverá uma nova chance, um novo amor, uma nova amizade. pra todo fim um recomeço.",
  "O maior problema do tolo é pensar que ele é alguma coisa. E ele tem razão, ele é tolo.",
  "E loucura jogar todas as chances de ser feliz fora, só porque uma tentativa fracassou.",
  "Que o seu amor possa vir com toda simplescidade, de dentro pra fora, de um para o outro.",
  "As coisas dando certo ou não, lave o cabelo, hidrate, vista o seu melhor look, tire foto e veja o quanto você é maravilhosa.",
  "Se eu pudesse eu te daria o mundo inteiro, mas como eu não posso, eu te dou uma parte dele: Eu.",
  "O segredo da vida, não é ter tudo que você quer, mas amar tudo que você tem.",
  "Os sentimentos de verdade, são apenas nossos. Ninguém copia, ninguém leva, ninguém divide.",
  "É melhor levar uma surra da sinceridade, do que um abraço da falsidade.",
  "Não, o amor não é raro, raras, são as pessoas que sabem amar.",
  "É loucura odiar todas as rosas, só porque uma te espetou.",
  "Certeza, é quando a ideia cansa de procurar e para.",
  "Se o primeiro e o último pensamento do dia for essa pessoa, se a vontade de ficar perto dela aperta o coração, agradeça, isso é amor.",
  "Toda mulher é santa, até se apaixonar.",
  "Em um mundo feito de aparência, feliz é aquele que é feito de verdade.",
  "Um coração feliz, é o resultado inevitável de um coração, cheio de amor.",
  "Uns deixam você ir, outros daria tudo pra você ficar.",
  "O que mais me impressiona nos fracos, é que eles precisam humilhar as pessoas pra se sentirem fortes.",
  "Seja a razão de alguém acreditar, que pessoas boas existem.",
  "Se você está atravessando mal momentos siga caminhando, afinal, o mal é o momento e não você.",
  "O amor, é o estágio mais elevado do sentimento. O homem só atinge a plenitude, quando ama.",
  "Não jogue fora quem te adora, vê se toma juízo.",
  "Quando você descobre o seu valor, nada mais te abala. A paz faz morada, o silêncio reina e a vida acontece.",
  "Só o tempo é capaz de entender um grande amor.",
  "More em seu amor próprio, pois é complicado pagar aluguel em coração alheio.",
  "Talvez eu seja enganado inúmeras vezes, mas não deixarei de acreditar que em algum lugar, alguém merece a minha confiança.",
  "More em seu amor próprio, pois é complicado pagar aluguel em corações alheios.",
  "Sentimento, é a linguagem que o coração usa, quando precisa mandar um recado.",
  "Não vou com a sua cara! Ué, e minha cara te chamou pra ir aonde.",
  "Amizade, é quando você não faz questão de você e se empresta pro outros.",
  "Não desista só porque está difícil, as melhores coisas da vida levam tempo, as outras, o tempo leva.",
  "Vergonha, é um pano preto que você quer pra se cobrir naquela hora.",
  "Angústia, é um nó muito apertado, bem no meio do sossego.",
  "Às vezes, dá vontade de largar tudo e sair correndo, mas nesse mundo não há saída de emergência, a única saída é ser forte.",
  "Amizades unilaterais, duram pouco tempo e só servem pra trazer tristeza e sentimentos de descaso.",
  "Tudo o que for pra você, mais cedo ou mais tarde, vai te encontrar.",
  "Faça como a águia, ouse, faça coisas diferentes, voe por cima dos obstáculos.",
  "Tem pessoas que não merecem suas lágrimas e muito menos o seu sorriso.",
  "Raiva: é quando o cachorro que mora em você mostra os dentes.",
  "Às vezes, o milagre são as pessoas boas que cruzam o nosso caminho.",
  "Pressentimento, é quando passa em você o trailer de um filme que pode ser que não exista.",
  "Não perca seu tempo investindo em relacionamento que só você se importa, só você procura, só você liga, só você manda Email.",
  "Ansiedade, é quando faltam muitos minutos para o que quer que seja.",
  "Amor, é quando a paixão não tem outro compromisso marcado.",
  "Um dos maiores erros que se pode cometer, é achar que o coração dos outros é igual ao seu.",
  "Se eu pudesse conversar com a sua alma eu diria: fique calma, tudo isso vai passar.",
  "Que o seu amor não dependa do tempo, nem da paisagem, nem da sorte e nem do dinheiro.",
  "Na vida, tudo passa. Mas nem tudo a gente esquece.",
  "Preocupação: é uma cola, que não deixa o que ainda não aconteceu, sair do seu pensamento.",
  "A atitude, é a expressão máxima do amor.",
  "Não perca seu tempo em um relacionamento que só você se importa, só você procura, só você liga, só você manda email.",
  "Interesse, é um ponto de exclamação, ou interrogação no final de um sentimento.",
  "Deus não falha, Deus não erra, Deus não atrasa. Ele cumprirá o que te prometeu.",
  "Amar, é sorrir por nada e ficar triste sem motivos.",
  "Quando chegar a sua vez de ser martelo, bata forte. Lembre-se: quando você foi prego, ninguém teve compaixão de você.",
  "A vida não é sobre esperar a tempestade passar, e sim, aprender a dançar na chuva.",
  "Se Jesus pudesse cantar uma música pra você hoje, qual música você gostaria de ouvir.",
  "Seja uma boa pessoa, mas não perca seu tempo tentando provar isso pra ninguém.",
  "Não desanime, tenha certeza de que a primavera vai voltar, trazendo folhas e flores.",
  "O amor maduro aceita a individualidade e a liberdade, enquanto a posse tenta extinguir a distancia e a diferença.",
  "Que a esperança venha nos lembrar, que amanhã tudo pode ser diferente, basta você acreditar.",
  "Às vezes, o milagre, são as pessoas boas que cruzam o nosso caminho.",
  "Quem aprende a dançar na chuva, rir do mal tempo.",
  "Indecisão: é quando você sabe muito bem o que quer, mas acha que deveria querer outra coisa.",
  "A gente vai crescendo e descobre, que o melhor da vida estás dentro de nós.",
  "Se não der certo hoje, amanhã a gente tenta de novo.",
  "Quando alguém semear maldade na sua vida, fique em paz, a colheita será dela.",
  "A saudade, é única coisa que o tempo não leva.",
  "Quando o amor se torna posse, é aí que mora o perigo.",
  "Se você tá cansado de recomeçar, pare de desistir.",
  "Quem gosta de você, sabe exatamente o seu valor.",
  "Às vezes, a gente só precisa ouvir uma boa música.",
  "Não acumule silêncios, às vezes, gritar faz bem ao coração.",
  "A maldade, é uma carta que sempre volta para o remetente.",
  "A saudade, é a única coisa que o tempo não leva.",
  "Não se pode confundir amor com posse, nem relacionamento com domínio.",
  "A vida me ensinou a dizer adeus as pessoas que eu amo, sem tirá-las do coração.",
  "Quando a mulher maravilha vai embora, o super-homem chora.",
  "Um dia sem sorriso, é um dia desperdiçado.",
  "Mesmo quebrado, Deus preferiu me consertar ao invés de me jogar fora.",
  "O amor fala, sem dizer uma só palavra.",
  "Deus não esquece ninguém, ele só está dando tempo até que estejamos preparados pra receber aquilo que ele está preparando pra a gente.",
  "Não questione os planos de DEUS, ele vê coisas que você não vê.",
  "Só Des tem a capacidade de ouvir uma alma que grita em silêncio.",
  "Aprenda a viver ou conviver com a falta, a perda, a ausência de. Certas coisas não vale a pena ter de volta.",
  "Nascer, é uma possibilidade, viver é um risco, mas envelhecer, é um privilégio.",
  "Olá gente boa, você que curte e comenta meus vídeos aqui no Instagram, me segue também dá essa força pro pai aí.",
  "É impossível progredir sem mudanças, e aqueles que não mudam suas mentes, não podem mudar nada.",
  "O nosso cérebro, é o maior brinquedo já criado. Nele encontramos os maiores segredos, inclusive o da felicidade.",
  "O amor de Deus, recarrega a alma.",
  "Mais do que máquina, precisamos de humanidade, mais do que inteligência precisamos de afeição e doçura.",
  "A oração, desliga a ansiedade e liga o milagre.",
  "Certos vínculos, assim como espinhos nos pés, só nos permitem caminhar melhor, quando nos livramos deles.",
  "Continue, às vezes o próximo passo, é o que muda tudo.",
  "Um dia, você será somente saudade, então, deixe o seu melhor por onde passar.",
  "Barco que tem Jesus, também passa por dificuldades, só não afunda.",
  "Eu sou o resultado de todas às vezes que não me permiti desistir. E você, quem é.",
  "Lágrimas, também são orações, elas vão até Deus, quando você não consegue falar.",
  "Mudar de caminho, não é fracasso, é coragem.",
  "Intuição, é quando o seu coração dá um pulinho no futuro e volta rápido.",
  "No fim Deus multiplica a sua bondade e a transforma em bençãos.",
  "Só abrace o que te faz sorrir, o resto, deixa ir.",
  "O amor, não bate em uma porta duas vezes, quando o amor vai embora, o coração chora.",
  "Existe um Deus, que do nada, faz tudo.",
  "Acredite: quando JESUS chega, alguma coisa acontece.",
  "Não há espelho melhor que reflita o ser humano, do que as suas atitudes.",
  "Deus está lutando por você, fique em silêncio.",
  "A maior bênção, não é ter tudo, é ter Deus em tudo.",
  "Às vezes, está fora do grupo não é exclusão, é livramento.",
  "Evolua tanto que os outros precisarão conhecer você de novo.",
  "A vida é feita de escolhas, até o silêncio é uma decisão.",
  "Às vezes na pressa, a gente nem percebe o quanto Deus tem cuidado da gente.",
  "O que eu aprendo, não me faz melhor do que ninguém, o que eu aprendo, me faz melhor do eu era.",
  "Assim como uma vírgula muda uma frase, uma atitude muda uma história.",
  "Tem coisas que Deus dá pra a gente aprender e tem coisas que ele só dá, quando a gente aprende.",
  "Há olhares que nos tocam muito mais do que qualquer mão poderia.",
  "Seja como Jó, que apesar de ver a maldade das pessoas, não se permitiu contaminar, continuou sendo bom.",
  "Esqueça o ontem, viva o hoje e deixa Deus decidir o amanhã.",
  "Nada é tão nosso, quanto os nossos sonhos.",
  "Levante com fé, viva com amor e termine o dia com gratidão.",
  "Antes de uma grande bênção, haverá sempre uma grande luta, confie no processo.",
  "O segredo é um só: fé em DEUS.",
  "Quando a fé encontra o propósito, o impossível vira caminho.",
  "Só não vê anjos, aqueles que não prestam atenção nas pessoas que Deus coloca em sua vida.",
  "Na vida tudo volta. Isso te conforta ou te assusta.",
  "O tempo, é a forma que Deus deixou pra dizer que nessa vida, tudo passa.",
  "Nem todo dia é fácil, mas todo dia é um presente de Deus.",
  "Às vezes, você nem percebe, mais a sua luz ilumina o caminho de muita gente.",
  "Um dia, você será somente saudade, então, faça o seu melhor por onde passar.",
  "Nem sempre você precisará contar o seu lado da história.",
  "Acalma o seu coração, Deus já está cuidando de tudo.",
  "Quando Deus mudar o seu caminho, não fique frustrado, ele sabe o que tem que depois da curva.",
  "Nem tudo depende do tempo, às vezes as coisas dependem, só de uma atitude.",
  "Já que estamos de passagem nessa vida, Deixemos boas pegadas.",
  "Jogaram terra em você, mal sabiam que você é semente.",
  "Liberta-te, de tudo o que deixa a sua vida pesada.",
  "Os dois maiores bens da vida: saúde e tempo. Invista na sua saúde e você terá mais tempo.",
  "Olhe para trás e Veja quantas tempestades você já venceu, não ouse desistir agora.",
  "Às vezes, tudo que precisamos, é de um novo começo.",
  "Ainda não te pediram desculpas e talvez nunca peçam, mas no seu coração você já perdoou, isso é ganhar a guerra sem precisar lutar.",
  "Bonita é a alma que coleciona cicatrizes, mas prefere espalhar amor.",
  "A paz que se dá, é a paz que se tem.",
  "O tempo, tem uma forma maravilhosa de nos mostrar o que realmente importa.",
  "Entre os altos e baixos da vida, jamais abandone a sua fé, seu sorriso e sua essência.",
  "A grande jogada da vida é deixar certas coisas de lado.",
  "Confie no propósito, mesmo sem entender o processo.",
  "Não é o que você tem, é o que você é.",
  "Assim é a vida: cada pedra uma lição, cada, dificuldade uma prova, cada alegria uma vitória, cada decepção, uma nova chance de recomeçar.",
  "Nunca espere algo pequeno de um Deus tão grande.",
  "Às vezes, a vida afasta alguém de você, não porque faltou amor, mas porque cada um precisava seguir caminhos diferentes.",
  "A maior conquista da vida, é está em paz.",
  "O corpo envelhece sem se sua permissão, mas a alma envelhece se você permitir.",
  "O dono do tempo, sabe a hora de mudar a sua história.",
  "Amigo, a gente não procura, o coração é que encontra.",
  "O máximo não se alcança fazendo mínimo.",
  "O tempo passa e nós descobrimos que está em paz, não tem preço, tem valor.",
  "Não há vagas, pra quem não aproveita as oportunidades.",
  "Não escute o que dizem, observe o que fazem.",
  "A decepção não mata, mas faz muito sentimento bom morrer.",
  "Aprendi a ser forte, quando percebi que teria que levantar sozinho.",
  "Quando te faltar forças, não esqueça quem é a fonte.",
  "A vida é uma tragédia, quando vista de perto, mas uma comédia, quando vista de longe.",
  "Se algum dia por acaso você se lembrar de mim, saiba que eu estou aqui, penso em você todos os dias, porque nunca te esqueci.",
  "Dos amores que eu tive você foi o mais importante, hoje meu coração acelerado bate cheio de saudade, por você viver distante.",
  "Nossas maiores vitória, vencemos em silêncio, nelas não ninguém nos aplaudindo, mas tem Deus nos honrando.",
  "No seu ventre, carrega o milagre da vida, no coração, um amor incondicional. Parabéns mamães pelo seu dia.",
  "Não tenha medo da mudança, ela assusta, mas pode ser a chave da porta que você almeja tanto abrir.",
  "Caçador que grita antes de atirar a flecha, volta pra casa com fome.",
  "Só as lagartas viram borboletas, as Víboras, continuam víboras.",
  "Ainda guardo na memória, as noites em claro que passamos, mesmo sem dormir os sonhos que sonhamos.",
  "O vento sempre muda de direção, um dia ele soprará a seu favor.",
  "A vida é uma grande colheita, onde você é fruto das suas plantações.",
  "Decepção, é o único sentimento que faz você abrir os olhos e fechar o coração.",
  "Se algum dia por acaso, sentires saudades sem fim, me avise por favor, só pra saber, que ainda gosta de mim.",
  "Deus não quer que você entenda, ele quer que você confie.",
  "Tem dia que o meu coração acelera com saudade de você no meu peito bate forte com vontade de te ver.",
  "A meta é ser melhor que ontem, não melhor que ninguém.",
  "A oração, não pra lembrar a Deus o que eu preciso, mas pra me lembrar de que Deus, é tudo que eu preciso.",
  "Se pensas em mim eu não sei, não posso responder, mas uma coisa eu sei: eu penso muito em você.",
  "Amigo a gente não procura, o coração é que encontra.",
  "Dizem que quando você chega na estação certa é que entende o motivo de ter perdido o trem tantas vezes, e isso não é sobre trem.",
  "Eu não conhecia o amor até te conhecer, pois foi você que me ensinou a amar e te querer.",
  "Às vezes, Deus usa alguém pra te salvar, ou usa você pra salvar alguém, ou usa os dois pra se salvarem.",
  "O Verdadeiro amor, permanece, nem que seja na saudade, por isso que o meu amor por você é amor de verdade.",
  "Não desista, às vezes é a última chave que abre a porta.",
  "Hoje eu acordei com saudades de você. Você bem que podia aparecer, nem que fosse em meus sonhos, de noite ou de dia, eu só queria te ver.",
  "Ainda ouço a sua voz ressoar em meus ouvidos, suavemente dizendo: eu te amo meu querido.",
  "Se eu pudesse, faria de tudo pra não te deixar partir, mas amar também é isso, por isso, te deixei ir.",
  "Eu espero sinceramente que essa saudade que vai e vem e que eu sinto por você todos os dias, você sinta sinceramente todos os dias, por mim também.",
  "Quem te largou no meio do oceano, não tem o direito de saber o que houve entre você e os tubarões e nem como você chegou a praia.",
  "Com você eu aprendi o que é felicidade, foi com você que eu descobri, o que é amar de verdade.",
  "Você precisa entender que pra Deus não existe distância, ele não vê circunstância, isso quem faz é você.",
  "Temos que aprender a ser sozinhos, pra quando alguém for embora, não parecer o fim do mundo.",
  "Se a dor do outro não doer em mim, eu desconheço o amor.",
  "Podem cortar as flores, mas nunca, nunca poderão deter a primavera.",
  "Dizem que quando você chega na estação certa é que você entende o motivo de ter perdido o trem tantas vezes, e isso não é sobre o trem.",
  "Não tenha medo de arriscar, se der certo você vence, se der errado, você aprende.",
  "O dia mais triste da minha vida, foi quando você foi embora, meu coração que só sorria, hoje triste só chora.",
  "Às vezes, o milagre não vem na velocidadade que você deseja, mas chega na hora que você precisa.",
  "Não tem como andar de mãos dadas, com o pé atrás, e isso é sobre confiança.",
  "Tem saudade, que não grita, não chama, não pede volta, só fica.",
  "A única certeza do amanhã, é que Deus estará lá.",
  "A amizade acaba, quando você descobre que o amigo era só você.",
  "A saudade é a presença constante, de alguém ausente.",
  "O inferno que eu passei, não tinha fogo nem demônio, tinha pessoas, que eu tanto amava.",
  "O tempo, tem uma forma maravilhosa de nos mostrar, o que realmente importa.",
  "Pra Deus não existe escudo, você não tem na verdade, noção da velocidade de que ele pode mudar tudo.",
  "Não demore muito pra perceber que é preciso pouco pra ser feliz.",
  "Não tenha medo de arriscar, se der certo, você vence, se der errado, você aprende.",
  "A vida é assim: uns te derrubam, outros te levantam, uns te fazem chorar, outros te fazem sorrir.",
  "Tem pessoas, que a gente tenta esquecer, mas o coração insiste em lembrar.",
  "Tem saudade que fica nos detalhes, nos horários vazios, nas coisasque não fazem sentido.",
  "Tem amores, que não vão embora, só ficam em silêncio dentro da gente.",
  "Acredite, não há só um dia que Deus não cuida de você.",
  "A saudade é uma dor calma mas, constante, que aperta o peito sem avisar.",
  "Nunca empreste seu guarda-chuva pra quem só lembra de você quando chove.",
  "A vida é assim: uns matam sentimentos, outros ressuscitam sentimentos.",
  "Há pessoas que te oferecem as estrelas e há outras, que te levam a elas.",
  "Não vale de nada, joelhos no chão, se você semeia maldade quando está de pé.",
  "Não é só acreditar, você tem que confiar, como nunca confiou, se Deus quiser você pisa onde ninguém mais pisou.",
  "A vida é assim: uns te ferem, outros te curam, uns te rejeitam outros te aceitam.",
  "Sempre que tiver uma oportunidade, seja uma luz na vida de alguém.",
  "No tempo certo a gente entende certos porquês.",
  "Tem dias, que a alma só quer ficar em silêncio.",
  "O barco balança pra testar quem fica e quem pula.",
  "Lentamente me tornando a pessoa que eu deveria ser há muito tempo.",
  "Sou vilão de muitas histórias mal contadas que não me interessa esclarecer.",
  "O amor é a dádiva que nós podemos modificar.",
  "Os abraços de Deus nas horas difíceis, Muda tudo.",
  "Trabalhe como se tudo dependesse de você, confie como se tudo dependesse de Deus.",
  "Faça o bem em silêncio, a sua ausência será sentida.",
  "Às vezes Deus não remove os seus problemas, ele abre caminhos através deles.",
  "Às vezes, Deus quebra seu coração, pra salvar sua alma.",
  "Todo dia eu aprendo um pouco mais, a me importar um pouco menos.",
  "Vá com as pernas tremendo, mas vá. Deixa o medo sentir medo da sua coragem.",
  "Nunca conte a ninguém mais do que ela precisa saber Baú aberto não protege tesouro.",
  "Cedo ou tarde a tempestade passa.",
  "O bem se faz em silêncio, o resto. o resto é teatro.",
  "Quem fala com Deus não fica sem resposta.",
  "Tanto a fé quanto o medo, exige que você acredite em algo que você não pode vê.",
  "A vontade de Deus é boa, perfeita e agradável. A permissão de Deus é consequências do livre arbítrio.",
  "Se não tentam fazer você ficar, talvez estejam esperando você ir.",
  "A distância não diminui a importância.",
  "Julgar uma pessoa não define quem ela é, muito pelo contrário, define quem você é.",
  "Há apenas um remédio para o amor, amar mais.",
  "Meu coração queria ir até você, mas eu expliquei pra ele que sem ele eu morro, ele me respondeu que sem você ele não vive.",
  "Em cada sorriso, em cada olhar, o amor se revela em sua forma mais pura.",
  "Você nunca será corajoso se não tiver sentido medo.",
  "Não deixe seus sonhos serem apenas sonhos.",
  "Quando você é uma boa pessoa, você não perde pessoas, elas quem te perdem.",
  "Não tenha medo de falhar, tenha medo de não não tentar.",
  "Nada antes nada depois, tudo no tempo de Deus.",
  "Jesus, é o amor que vive em nós.",
  "E preciso coragem pra amar alguém. Felizmente sou uma pessoa destemida e não me canso de mostrar o quanto te amo.",
  "Todo mundo fala que nenhuma mulher esquece o seu primeiro amor, mas o homem também não.",
  "Amizade não é uma coisa grande, são milhões de coisas pequenas.",
  "Você foi perdoado, então aprenda a perdoar.",
  "Nada é melhor do que um amor correspondido.",
  "Há tanta gente ruim de olho na sua felicidade. Aprenda a não deixar qualquer um a par da sua vida.",
  "Nunca se importe com pessoas que falam mal de você por trás. Lembre-se por trás do portão qualquer cachorro late.",
  "Nunca exijo frutos daquilo que você planta mas não rega.",
  "Nada é melhor pra saúde, do que um amor correspondido.",
  "Ame e pronto, não se preocupe com resposta. Até porque o amor, dificilmente iremos perceber.",
  "Eu poderia durar mais cem anos, viver mais cem vidas, e jamais eu iria esquecer o meu primeiro amor.",
  "O que que eu quero no fim, é que as minhas mãos tenham conseguido te oferecer amor.",
  "É preciso coragem pra amar alguém. Felizmente eu sou uma pessoa destemida e não me canso de mostrar o quanto te amo.",
  "Como são sábios aqueles que se entregam as loucuras do amor.",
  "Natal, é tempo de comemorar a vida, espalhar o amor e semear esperança. Feliz Natal.",
];

/** Uma frase ao acaso, evitando repetir a ultima que apareceu. */
export function sortearFrase(anterior?: string): string {
  if (FRASES.length < 2) return FRASES[0] ?? '';
  let escolhida = anterior;
  while (escolhida === anterior) {
    escolhida = FRASES[Math.floor(Math.random() * FRASES.length)];
  }
  return escolhida!;
}
